version: '3.5'
services:
  autossh:
    container_name: autossh
    build:
      context: .
      dockerfile: autossh-with-envs.dockerfile
      args:
        SSH_PRV_KEY: 
    environment:
      SSH_TUNNEL_PORT: "ssh port"
      SSH_TUNNEL_MODE: "-L or -R"
      SSH_TUNNEL_REMOTEPORT: "remote port (for -L mode)"
      SSH_TUNNEL_IP: "your endpoint"
      SSH_TUNNEL_LOCALPORT: "local port (for -L mode)"
      SSH_TUNNEL_USER: "user of your endpoint"
      SSH_TUNNEL_HOST: "your endpoint"
    network_mode: host
    restart: unless-stopped
